target 'ActivityPlusTwo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ActivityPlusTwo

  target 'ActivityPlusTwoTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end

end
