platform :ios, '7.0'
xcodeproj 'GuessTheNumber/GuessTheNumber.xcodeproj'

target :GuessTheNumberXCTests, :exclusive => true do
  pod 'Kiwi/XCTest'
end

post_install do |installer|
  installer.project.targets.each do |target|
    puts "Processing target: #{target.name}..."
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "$(ARCHS_STANDARD_32_BIT)"
    end
  end
end
