# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.ssh.pty = true

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y git clang libicu-dev

    wget https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a/swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a-ubuntu14.04.tar.gz
    tar xzvf swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a-ubuntu14.04.tar.gz

    echo "export PATH=/home/vagrant/swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a-ubuntu14.04/usr/bin:$PATH" >> ~/.profile

    echo "export LD_LIBRARY_PATH=/home/vagrant/swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a-ubuntu14.04/usr/lib/swift/linux/:$LD_LIBRARY_PATH" >> ~/.profile

    swift --version
  SHELL
end
